Small fixes on punctuation
Comadreja/js-for-gamedev pull request #2
Opened 2017-05-22 17:16 UTC by delapuente

2017-05-22 17:46 UTC, Comadreja reviewed
Me corrijo: la "norma" que he mencionado antes no aplica al inglés escrito en general, sino que se trata específicamente de un estilo de puntuación americano. Estoy bastante seguro de que hay alguna escuela tipográfica británica que también la recomienda, pero en general el en-UK sigue el mismo criterio nuestro. Por consistencia con el uso de ortografía y vocabulario americanos (en los pocos casos en los que ha sido necesario elegir), mantendría el estilo americano. Excepciones notables son en el formato de hipervínculos (no hay un criterio oficial, pero todas las recomendaciones que he leído son en contra de incluir el signo de puntuación que siga), así como las inclusiones de texto formateado como código dentro de párrafos. Lo que sí voy a aceptar son tus cambios a los segmentos de código; mis cambios al original proceden de haber hecho el primer procesado del texto en Atom, que no me hacía el color coding correctamente si no le ponía el ``` y el sh en líneas separadas.

2017-05-22 17:57 UTC, Comadreja commented on en/02-javascript/0202-modelo-de-datos/index.md
> -You are going to be experimenting with JavaScript, so you will need a quick way of inspecting expressions and obtaining feedback on what you are doing. The best way is to use the **Node console.** Fo
Puntuación americana.

2017-05-22 17:59 UTC, Comadreja commented on en/02-javascript/0202-modelo-de-datos/index.md
> +```sh
Aprobado.

2017-05-22 18:00 UTC, Comadreja commented on en/02-javascript/0202-modelo-de-datos/index.md
> +```sh
Aprobado.

2017-05-22 18:07 UTC, Comadreja commented on en/02-javascript/0202-modelo-de-datos/index.md
> -You are going to be experimenting with JavaScript, so you will need a quick way of inspecting expressions and obtaining feedback on what you are doing. The best way is to use the **Node console.** Fo
Como te he comentado antes, el criterio americano ante puntuación coexistente con énfasis, paréntesis o entrecomillados es incluir el signo de puntuación. Las excepciones son el formato de hipervínculo (aparte del caso obvio de las URLs, aunque no encuentro ninguna fuente oficial, el consenso parece estar en dejar el signo de puntuación fuera) y una que he hecho personalmente para las inclusiones de código dentro del texto, que a menudo van entrecomilladas.

2017-05-22 18:08 UTC, Comadreja requested changes

2017-05-22 18:08 UTC, Comadreja commented on en/02-javascript/0202-modelo-de-datos/index.md
> -```
Los cambios a los segmentos de código te los apruebo trivialmente, todos los que yo introduje respecto al original son a causa de este problema de Atom.

2017-05-23 10:34 UTC, delapuente commented
I'm closing my PR in favor of #3

2017-05-23 10:34 UTC, closed without merging